[[config]]
path = "../configs/datasets/bdd100k/sem_seg.toml"

[[config]]
path = "../configs/models/mmsegmentation/deeplabv3plus_R_18_D8.toml"

[model]
    [model.optimizer]
    type = "SGD"
    lr = 0.01

    [model.lr_scheduler]
    type = "PolyLRScheduler"
    mode = "step"
    kwargs = {"max_steps" = 10, "power" = 0.9, "min_lr" = 0.0001}

[launch]
samples_per_gpu = 1
workers_per_gpu = 0

[trainer]
max_steps = 1