[model]
type = "PanopticSegmentor"
category_mapping = {"pedestrian" = 0, "rider" = 1, "bicycle" = 2, "bus" = 3, "car" = 4, "caravan" = 5, "motorcycle" = 6, "trailer" = 7, "train" = 8, "truck" = 9}
    [model.detection]
    type = "MMTwoStageDetector"
    model_base = "vis4d/engine/testcases/configs/models/mmdetection/mmdet_cfg_maskrcnn_r18fpn.py"
    pixel_mean = [123.675, 116.28, 103.53]
    pixel_std = [58.395, 57.12, 57.375]
    backbone_output_names = ["p2", "p3", "p4", "p5", "p6"]

    [model.seg_head]
    type = "MMSegDecodeHead"
    category_mapping = {"dynamic" = 0, "ego vehicle" = 1, "ground" = 2, "static" = 3, "parking" = 4, "rail track" = 5, "road" = 6, "sidewalk" = 7, "bridge" = 8, "building" = 9, "fence" = 10, "garage" = 11, "guard rail" = 12, "tunnel" = 13, "wall" = 14, "banner" = 15, "billboard" = 16, "lane divider" = 17, "parking sign" = 18, "pole" = 19, "polegroup" = 20, "street light" = 21, "traffic cone" = 22, "traffic device" = 23, "traffic light" = 24, "traffic sign" = 25, "traffic sign frame" = 26, "terrain" = 27, "vegetation" = 28, "sky" = 29}
    mm_cfg = "vis4d/engine/testcases/configs/models/panoptic/fpn_decode_head.py"

    [model.pan_head]
    type = "SimplePanopticHead"
