[[config]]
path = "../configs/datasets/bdd100k/ins_seg.toml"

[[config]]
path = "../configs/models/mmdetection/mask_rcnn_R_50_FPN.toml"

[launch]
samples_per_gpu = 1
workers_per_gpu = 0

[trainer]
max_steps = 50
log_every_n_steps = 50
