[[train]]
name = "bdd100k_seg_track_sample_train"
type = "BDD100K"
annotations = "vist/engine/testcases/track/bdd100k-samples/labels/"
data_root = "vist/engine/testcases/track/bdd100k-samples/images/"
config_path = "seg_track"
num_processes = 0
cache_as_binary = true
    [train.dataloader]
    compute_global_instance_ids = true
    fields_to_load = ["boxes2d", "insmasks"]

        [train.dataloader.ref_sampling]
        type = 'uniform'
        scope = 2
        num_ref_imgs = 1
        skip_nomatch_samples = true

    [[train.dataloader.transformations]]
    type = "Resize"
    shape = [720, 1280]

    [[train.dataloader.transformations]]
    type = "KorniaAugmentationWrapper"
    kornia_type = "RandomHorizontalFlip"
    prob = 0.5

[[train]]
name = "bdd100k_ins_seg_sample_train"
type = "COCO"
annotations = "vist/engine/testcases/detect/bdd100k-samples/annotation_coco.json"
data_root = "vist/engine/testcases/detect/bdd100k-samples/images/"
config_path = "vist/engine/testcases/detect/bdd100k-samples/ins_seg_config.toml"
num_processes = 0
    [train.dataloader]
    fields_to_load = ["boxes2d", "insmasks"]

        [train.dataloader.ref_sampling]
        scope = 0
        num_ref_imgs = 1

    [[train.dataloader.transformations]]
    type = "Resize"
    shape = [720, 1280]

    [[train.dataloader.transformations]]
    type = "KorniaAugmentationWrapper"
    kornia_type = "RandomHorizontalFlip"
    prob = 0.5

[[test]]
name = "bdd100k_sample_val"
type = "BDD100K"
annotations = "vist/engine/testcases/track/bdd100k-samples/labels/"
data_root = "vist/engine/testcases/track/bdd100k-samples/images/"
eval_metrics = ["detect", "track", "ins_seg", "seg_track"]
config_path = "seg_track"
num_processes = 0
    [test.dataloader]
    fields_to_load = ["boxes2d", "insmasks"]

        [[test.dataloader.transformations]]
        type = "Resize"
        shape = [720, 1280]
