[model]
type = "QDGeneralizedRCNN"
keyframe_selection = "random"
    [model.detection]
    type = "D2GeneralizedRCNN"
    model_base = "faster-rcnn/r50-fpn"
    num_classes = 8

    [model.track_graph]
    type = "QDTrackGraph"
    keep_in_memory = 10  # timesteps

    [[model.losses]]
    type = "MultiPosCrossEntropyLoss"
    loss_weight = 0.25

    [[model.losses]]
    type = "EmbeddingDistanceLoss"
    loss_weight = 1.0

    [model.similarity]
    type = "QDSimilarityHead"
    num_classes = 0
    in_dim = 256
    num_convs = 4
    conv_out_dim = 256
    num_fcs = 1
    fc_out_dim = 1024
    embedding_dim = 256
    norm = "GN"
    proposal_append_gt = true

        [model.similarity.proposal_pooler]
        type = "D2RoIPooler"
        pooling_op = "ROIAlignV2"
        resolution = [7, 7]
        strides = [4, 8, 16, 32]
        sampling_ratio = 0

        [model.similarity.proposal_sampler]
        type = "CombinedSampler"
        batch_size_per_image = 256
        positive_fraction = 0.5
        pos_strategy = "instance_balanced"
        neg_strategy = "iou_balanced"

        [model.similarity.proposal_matcher]
        type = "MaxIoUMatcher"
        thresholds = [0.3, 0.5]
        labels = [0, -1, 1]
        allow_low_quality_matches = false

[solver]
images_per_batch = 1
lr_policy = "WarmupMultiStepLR"
base_lr = 0.02
steps = [1000, 2000]
max_iters = 1
checkpoint_period = 2000
eval_period = 1

[[train]]
name = "bdd100k_track_sample_train"
type = "scalabel_video"
annotations = "openmt/track/testcases/bdd100k-samples/labels/"
data_root = "openmt/track/testcases/bdd100k-samples/images/"

[[train]]
name = "bdd100k_det_sample_train"
type = "scalabel_video"
annotations = "openmt/detect/testcases/bdd100k-samples/annotation.json"
data_root = "openmt/detect/testcases/bdd100k-samples/images/"

[[test]]
name = "bdd100k_track_sample_val"
type = "scalabel_video"
annotations = "openmt/track/testcases/bdd100k-samples/labels/"
data_root = "openmt/track/testcases/bdd100k-samples/images/"

[dataloader]
num_workers = 0
sync_classes_to_intersection = true
    [dataloader.sampling_cfg]
    type = 'uniform'
    scope = 2
    num_ref_imgs = 1

[launch]
weights = "detectron2"