[[train]]
name = "bdd100k_track_train"
type = "BDD100K"
annotations = "data/bdd100k/labels/box_track_20/train/"
data_root = "data/bdd100k/images/track/train/"
config_path = "box_track"
num_processes = 0
cache_as_binary = true
    [train.sample_mapper]
    skip_empty_samples = true

    [train.ref_sampler]
    type = 'uniform'
    scope = 3
    num_ref_imgs = 1
    skip_nomatch_samples = true

    [[train.sample_mapper.transformations]]
    type = "Resize"
    shape = [720, 1280]

    [[train.sample_mapper.transformations]]
    type = "KorniaAugmentationWrapper"
    kornia_type = "RandomHorizontalFlip"
    prob = 0.5


[[train]]
name = "bdd100k_det_train"
type = "BDD100K"
annotations = "data/bdd100k/labels/det_20/det_train.json"
data_root = "data/bdd100k/images/100k/train/"
config_path = "det"
num_processes = 0
cache_as_binary = true
    [train.sample_mapper]
    skip_empty_samples = true

    [train.ref_sampler]
    scope = 0
    num_ref_imgs = 1

    [[train.sample_mapper.transformations]]
    type = "Resize"
    shape = [720, 1280]

    [[train.sample_mapper.transformations]]
    type = "KorniaAugmentationWrapper"
    kornia_type = "RandomHorizontalFlip"
    prob = 0.5

[[test]]
name = "bdd100k_track_val"
type = "BDD100K"
annotations = "data/bdd100k/labels/box_track_20/val/"
data_root = "data/bdd100k/images/track/val/"
eval_metrics = ["detect", "track"]
config_path = "box_track"
num_processes = 0
cache_as_binary = true
    [[test.sample_mapper.transformations]]
    type = "Resize"
    shape = [720, 1280]
