[[train]]
name = "bdd100k_seg_track_train"
type = "BDD100K"
annotations = "data/bdd100k/labels/seg_track_20_rle/train/"
data_root = "data/bdd100k/images/hdf5s/track_train.hdf5"
config_path = "seg_track"
num_processes = 0
cache_as_binary = true
    [train.sample_mapper]
    fields_to_load = ["boxes2d", "instance_masks"]
    skip_empty_samples = true

    [train.sample_mapper.data_backend]
    type = "HDF5Backend"

    [train.ref_sampler]
    type = 'uniform'
    scope = 3
    num_ref_imgs = 1
    skip_nomatch_samples = true

    [[train.sample_mapper.transformations]]
    type = "Resize"
    shape = [720, 1280]

    [[train.sample_mapper.transformations]]
    type = "KorniaAugmentationWrapper"
    kornia_type = "RandomHorizontalFlip"
    prob = 0.5

[[test]]
name = "bdd100k_seg_track_val"
type = "BDD100K"
annotations = "data/bdd100k/labels/seg_track_20_rle/val/"
data_root = "data/bdd100k/images/hdf5s/track_val.hdf5"
eval_metrics = ["detect", "track", "ins_seg", "seg_track"]
config_path = "seg_track"
num_processes = 0
validate_frames = true
cache_as_binary = true
    [test.sample_mapper]
    fields_to_load = ["boxes2d", "instance_masks"]

    [test.sample_mapper.data_backend]
    type = "HDF5Backend"

    [[test.sample_mapper.transformations]]
    type = "Resize"
    shape = [720, 1280]
