[[train]]
name = "bdd100k_det_train"
type = "BDD100K"
annotations = "data/bdd100k/labels/det_20/det_train.json"
data_root = "data/bdd100k/images/100k/train/"
config_path = "det"
cache_as_binary = true
    [train.dataloader]
    skip_empty_samples = true

    [train.dataloader.ref_sampling]
    type = 'uniform'
    scope = 1
    num_ref_imgs = 0

    [[train.dataloader.transformations]]
    type = "Resize"
    shape = [720, 1280]

    [[train.dataloader.transformations]]
    type = "KorniaAugmentationWrapper"
    kornia_type = "RandomHorizontalFlip"
    prob = 0.5

[[test]]
name = "bdd100k_det_val"
type = "BDD100K"
annotations = "data/bdd100k/labels/det_20/det_val.json"
data_root = "data/bdd100k/images/100k/val/"
eval_metrics = ["detect"]
config_path = "det"
cache_as_binary = true
    [[test.dataloader.transformations]]
    type = "Resize"
    shape = [720, 1280]
