[[train]]
name = "bdd100k_drivable_train"
type = "BDD100K"
annotations = "data/bdd100k/labels/drivable_train_rle.json"
data_root = "data/bdd100k/images/100k/train"
config_path = "drivable"
num_processes = 0
cache_as_binary = true
    [train.category_mapping]
    semantic_masks = {"direct" = 0, "alternative" = 1, "background" = 2}

    [train.sample_mapper]
    fields_to_load = ["semantic_masks"]
    skip_empty_samples = true
    bg_as_class = true

    [train.sample_mapper.data_backend]
    type = "HDF5Backend"

    [[train.sample_mapper.transformations]]
    type = "Resize"
    keep_ratio = true
    shape = [720, 1280]
    scale_range = [0.5, 2.0]

    [[train.sample_mapper.transformations]]
    type = "RandomCrop"
    crop_type = "absolute"
    shape = [512, 1024]
    cat_max_ratio = 0.75

    [[train.sample_mapper.transformations]]
    type = "KorniaAugmentationWrapper"
    kornia_type = "RandomHorizontalFlip"
    prob = 0.5

    [[train.sample_mapper.transformations]]
    type = "KorniaColorJitter"
    kornia_type = "ColorJitter"
    kwargs = {"brightness" = [0.875, 1.125], "contrast" = [0.5, 1.5], "saturation" = [0.5, 1.5], "hue" = [-0.1, 0.1]}

[[test]]
name = "bdd100k_drivable_val"
type = "BDD100K"
annotations = "data/bdd100k/labels/drivable_val_rle.json"
data_root = "data/bdd100k/images/100k/val"
eval_metrics = ["sem_seg"]
config_path = "drivable"
num_processes = 0
cache_as_binary = true
    [test.category_mapping]
    semantic_masks = {"direct" = 0, "alternative" = 1, "background" = 2}

    [test.sample_mapper]
    fields_to_load = ["semantic_masks"]
    bg_as_class = true

    [test.sample_mapper.data_backend]
    type = "HDF5Backend"

    [[test.sample_mapper.transformations]]
    type = "Resize"
    shape = [720, 1280]