[[train]]
name = "bdd100k_sem_seg_sample_train"
type = "Scalabel"
annotations = "data/bdd100k/labels/sem_seg_train_rle.json"
data_root = "data/bdd100k/images/hdf5s/10k_train.hdf5"
config_path = "configs/base/configs/sem_seg.toml"
cache_as_binary = true
    [train.dataloader]
    fields_to_load = ["semantic_masks"]

    [train.dataloader.data_backend]
    type = "HDF5Backend"

    [train.dataloader.ref_sampling]
    type = 'uniform'
    scope = 1
    num_ref_imgs = 0

    [[train.dataloader.transformations]]
    type = "Resize"
    keep_ratio = true
    shape = [720, 1280]
    scale_range = [0.5, 2.0]

    [[train.dataloader.transformations]]
    type = "RandomCrop"
    crop_type = "absolute"
    shape = [512, 1024]

    [[train.dataloader.transformations]]
    type = "KorniaAugmentationWrapper"
    kornia_type = "RandomHorizontalFlip"
    prob = 0.5

    [[train.dataloader.transformations]]
    type = "KorniaColorJitter"
    kornia_type = "ColorJitter"
    kwargs = {"brightness" = [0.8, 1.2], "contrast" = [0.5, 1.5], "saturation" = [0.5, 1.5]}

[[test]]
name = "bdd100k_sem_seg_sample_val"
type = "Scalabel"
annotations = "data/bdd100k/labels/sem_seg_val_rle.json"
data_root = "data/bdd100k/images/hdf5s/10k_val.hdf5"
config_path = "configs/base/configs/sem_seg.toml"
cache_as_binary = true
eval_metrics = ["sem_seg"]
    [test.dataloader]
    fields_to_load = ["semantic_masks"]

    [test.dataloader.data_backend]
    type = "HDF5Backend"

    [[test.dataloader.transformations]]
    type = "Resize"
    shape = [720, 1280]
