[[train]]
name = "bdd100k_ins_seg_train"
type = "BDD100K"
annotations = "data/bdd100k/labels/ins_seg_train_rle.json"
data_root = "data/bdd100k/images/hdf5s/10k_train.hdf5"
config_path = "ins_seg"
cache_as_binary = true
    [train.sample_mapper]
    fields_to_load = ["boxes2d", "instance_masks"]
    skip_empty_samples = true

    [train.sample_mapper.data_backend]
    type = "HDF5Backend"

    [train.ref_sampler]
    type = 'uniform'
    scope = 1
    num_ref_imgs = 0

    [[train.sample_mapper.transformations]]
    type = "Resize"
    shape = [720, 1280]

    [[train.sample_mapper.transformations]]
    type = "KorniaAugmentationWrapper"
    kornia_type = "RandomHorizontalFlip"
    prob = 0.5

[[test]]
name = "bdd100k_ins_seg_val"
type = "BDD100K"
annotations = "data/bdd100k/labels/ins_seg_val_rle.json"
data_root = "data/bdd100k/images/hdf5s/10k_val.hdf5"
eval_metrics = ["detect", "ins_seg"]
config_path = "ins_seg"
cache_as_binary = true
    [test.sample_mapper]
    fields_to_load = ["boxes2d", "instance_masks"]

    [test.sample_mapper.data_backend]
    type = "HDF5Backend"

    [[test.sample_mapper.transformations]]
    type = "Resize"
    shape = [720, 1280]
