[[train]]
name = "crowdhuman_trainval"
type = "Scalabel"
annotations = "data/CrowdHuman/trainval/trainval_scalabel.json"
data_root = "data/CrowdHuman/trainval"
num_processes = 0
    [train.sample_mapper]
    clip_bboxes_to_image = false
    skip_empty_samples = true

    [train.ref_sampler]
    strategy = 'uniform'
    scope = 0
    num_ref_imgs = 1

    [[train.sample_mapper.transformations]]
    type = "Resize"
    shape = [800, 1440]
    scale_range = [0.8, 1.2]
    keep_ratio = true

    [[train.sample_mapper.transformations]]
    type = "RandomCrop"
    shape = [800, 1440]

    [[train.sample_mapper.transformations]]
    type = "KorniaAugmentationWrapper"
    kornia_type = "RandomHorizontalFlip"
    prob = 0.5

    [[train.sample_mapper.transformations]]
    type = "KorniaColorJitter"
    kwargs = {"brightness" = [0.875, 1.125], "contrast" = [0.5, 1.5], "saturation" = [0.5, 1.5], "hue" = [-0.1, 0.1]}

[[train]]
name = "mot17_train"
type = "Scalabel"
data_root = "data/MOT17/train"
annotations = "data/MOT17/train/train_scalabel.json"
num_processes = 0
    [train.sample_mapper]
    clip_bboxes_to_image = false
    skip_empty_samples = true

    [train.ref_sampler]
    strategy = 'uniform'
    scope = 10
    num_ref_imgs = 1
    skip_nomatch_samples = true

    [[train.sample_mapper.transformations]]
    type = "Resize"
    shape = [800, 1440]
    scale_range = [0.8, 1.2]
    keep_ratio = true

    [[train.sample_mapper.transformations]]
    type = "RandomCrop"
    shape = [800, 1440]

    [[train.sample_mapper.transformations]]
    type = "KorniaAugmentationWrapper"
    kornia_type = "RandomHorizontalFlip"
    prob = 0.5

    [[train.sample_mapper.transformations]]
    type = "KorniaColorJitter"
    kwargs = {"brightness" = [0.875, 1.125], "contrast" = [0.5, 1.5], "saturation" = [0.5, 1.5], "hue" = [-0.1, 0.1]}

[[test]]
name = "mot17_val"
type = "MOTChallenge"
data_root = "data/MOT17/train"
annotations = "data/MOT17/train/val_scalabel.json"
eval_metrics = ["detect", "track"]
num_processes = 0
    [test.sample_mapper]
    clip_bboxes_to_image = false

    [[test.sample_mapper.transformations]]
    type = "Resize"
    shape = [800, 1440]
    keep_ratio = true

