[[train]]
name = "mot17_train"
type = "Scalabel"
data_root = "data/MOT17/train"
annotations = "data/MOT17/train/train_scalabel.json"
num_processes = 0
    [train.dataloader]
    clip_bboxes_to_image = false
    skip_empty_samples = true

    [train.dataloader.ref_sampling]
    type = 'uniform'
    scope = 10
    num_ref_imgs = 1
    skip_nomatch_samples = true

    [[train.dataloader.transformations]]
    type = "Resize"
    shape = [1088, 1088]
    scale_range = [0.8, 1.2]
    keep_ratio = true

    [[train.dataloader.transformations]]
    type = "RandomCrop"
    shape = [1088, 1088]

    [[train.dataloader.transformations]]
    type = "KorniaAugmentationWrapper"
    kornia_type = "RandomHorizontalFlip"
    prob = 0.5

    [[train.dataloader.transformations]]
    type = "KorniaColorJitter"
    kwargs = {"brightness" = [0.8, 1.2], "contrast" = [0.5, 1.5], "saturation" = [0.5, 1.5]}

[[test]]
name = "mot17_val"
type = "Scalabel"
data_root = "data/MOT17/train"
annotations = "data/MOT17/train/val_scalabel.json"
eval_metrics = ["detect", "track"]
num_processes = 0
    [test.dataloader]
    clip_bboxes_to_image = false

    [[test.dataloader.transformations]]
    type = "Resize"
    shape = [1088, 1088]
    keep_ratio = true
