[[train]]
name = "mot20_train"
type = "Scalabel"
data_root = "data/MOT20/train"
annotations = "data/MOT20/train/train_scalabel.json"
num_processes = 0
    [train.sample_mapper]
    skip_empty_samples = true

    [train.sample_mapper.data_backend]
    type = "HDF5Backend"

    [train.ref_sampler]
    strategy = 'uniform'
    scope = 10
    num_ref_imgs = 1
    skip_nomatch_samples = true

    [[train.sample_mapper.transformations]]
    type = "Resize"
    shape = [896, 1600]
    scale_range = [0.8, 1.2]
    keep_ratio = true

    [[train.sample_mapper.transformations]]
    type = "RandomCrop"
    shape = [896, 1600]

    [[train.sample_mapper.transformations]]
    type = "KorniaAugmentationWrapper"
    kornia_type = "RandomHorizontalFlip"
    prob = 0.5

    [[train.sample_mapper.transformations]]
    type = "KorniaColorJitter"
    kwargs = {"brightness" = [0.875, 1.125], "contrast" = [0.5, 1.5], "saturation" = [0.5, 1.5], "hue" = [-0.1, 0.1]}

[[test]]
name = "mot20_val"
type = "MOTChallenge"
data_root = "data/MOT20/train"
annotations = "data/MOT20/train/val_scalabel.json"
eval_metrics = ["detect", "track"]
num_processes = 0
    [test.sample_mapper.data_backend]
    type = "HDF5Backend"

    [[test.sample_mapper.transformations]]
    type = "Resize"
    shape = [896, 1600]
    keep_ratio = true
