[[train]]
name = "nuscenes_train"
type = "NuScenes"
data_root = "data/nuscenes"
version = "v1.0-trainval"
split = "train"
add_non_key = false
annotations = "data/nuscenes/scalabel_train.json"
cache_as_binary = true
    [train.sample_mapper]
    fields_to_load = ["boxes2d", "boxes3d", "intrinsics", "extrinsics", "lidar"]
    skip_empty_samples = true

    [train.ref_sampler]
    scope = 3
    num_ref_imgs = 1

    [[train.sample_mapper.transformations]]
    type = "Resize"
    shape = [900, 1600]

    [[train.sample_mapper.transformations]]
    type = "KorniaRandomHorizontalFlip"
    prob = 0.5

[[test]]
name = "nuscenes_val"
type = "NuScenes"
data_root = "data/nuscenes"
version = "v1.0-trainval"
split = "val"
add_non_key = true
annotations = "data/nuscenes/scalabel_val_full.json"
eval_metrics = ["detect_3d", "track_3d"]
cache_as_binary = true
    [test.sample_mapper]
    fields_to_load = ["boxes2d", "boxes3d", "intrinsics", "extrinsics"]

    [[test.sample_mapper.transformations]]
    type = "Resize"
    shape = [900, 1600]
