[[train]]
name = "nuscenes_mini_train"
type = "NuScenes"
data_root = "data/nuscenes"
version = "v1.0-mini"
split = "mini_train"
add_non_key = false
use_lidar = true
annotations = "data/nuscenes/scalabel_mini_train.json"
cache_as_binary = true
    [train.dataloader]
    fields_to_load = ["boxes2d", "boxes3d", "intrinsics", "extrinsics"]
    skip_empty_samples = true

    [train.dataloader.ref_sampling]
    scope = 3
    num_ref_imgs = 1

    [[train.dataloader.transformations]]
    type = "Resize"
    kwargs = {"shape" = [900, 1600]}

    [[train.dataloader.transformations]]
    type = "RandomHorizontalFlip"
    kwargs = {"p" = 0.5}

[[test]]
name = "nuscenes_mini_val"
type = "NuScenes"
data_root = "data/nuscenes"
version = "v1.0-mini"
split = "mini_val"
add_non_key = true
annotations = "data/nuscenes/scalabel_mini_val_full.json"
cache_as_binary = true
    [test.dataloader]
    fields_to_load = ["boxes2d", "boxes3d", "intrinsics", "extrinsics"]

    [[test.dataloader.transformations]]
    type = "Resize"
    kwargs = {"shape" = [900, 1600]}
