[[config]]
path = "../configs/datasets/kitti/track.toml"

[[config]]
path = "../configs/models/mmdetection/qd3dt_R_50_FPN.toml"

[model]
category_mapping = {"car" = 0, "pedestrian" = 1, "cyclist" = 2}
    [model.optimizer]
    type = "SGD"
    lr = 0.005
    kwargs = {"momentum" = 0.9, "weight_decay" = 0.0001}

    [model.lr_scheduler]
    type = "MultiStepLR"
    kwargs = {"milestones" = [8, 11]}

[launch]
samples_per_gpu = 1
workers_per_gpu = 0

[trainer]
max_steps = 1
log_every_n_steps = 50
check_val_every_n_epoch = 10