[[config]]
path = "../configs/datasets/kitti/track.toml"

[[config]]
path = "../configs/models/mmdetection/qdtrack_R_50_FPN.toml"

[model]
category_mapping = {"car" = 0, "pedestrian" = 1, "cyclist" = 2}
    [model.lr_scheduler]
    type = "StepLR"
    mode = "step"
    warmup = "exponential"
    kwargs = {"step_size" = 10}

[launch]
samples_per_gpu = 1
workers_per_gpu = 0

[trainer]
max_steps = 1
