[[train]]
name = "kitti_sample_train"
type = "KITTI"
data_root = "vis4d/engine/testcases/track/kitti-samples/"
annotations = "vis4d/engine/testcases/track/kitti-samples/tracking_training.json"
num_processes = 0
    [train.sample_mapper]
    image_channel_mode = "RGB"
    fields_to_load = ["boxes2d", "boxes3d", "intrinsics", "extrinsics", "lidar"]
        [train.ref_sampler]
        strategy = 'uniform'
        scope = 2
        num_ref_imgs = 1
        skip_nomatch_samples = true

    [[train.sample_mapper.transformations]]
    type = "Resize"
    shape = [375, 1242]

    [[train.sample_mapper.transformations]]
    type = "RandomCrop"
    crop_type = "relative"
    shape = [0.8, 0.9]

    [[train.sample_mapper.transformations]]
    type = "KorniaRandomHorizontalFlip"
    prob = 0.5

[[test]]
name = "kitti_sample_val"
type = "KITTI"
data_root = "vis4d/engine/testcases/track/kitti-samples/"
annotations = "vis4d/engine/testcases/track/kitti-samples/tracking_training.json"
validate_frames = true
num_processes = 0
multi_sensor_inference = false
eval_metrics = ["detect", "track"]
    [test.sample_mapper]
    fields_to_load = ["boxes2d", "boxes3d", "intrinsics", "extrinsics"]
    image_channel_mode = "RGB"

    [[test.sample_mapper.transformations]]
    type = "Resize"
    shape = [720, 1280]


[[test]]
name = "kitti_sample_val_multi_sensor"
type = "KITTI"
data_root = "vis4d/engine/testcases/track/kitti-samples/"
annotations = "vis4d/engine/testcases/track/kitti-samples/tracking_training.json"
validate_frames = true
num_processes = 0
eval_metrics = []
    [test.sample_mapper]
    fields_to_load = ["boxes2d", "boxes3d", "intrinsics", "extrinsics"]
    image_channel_mode = "RGB"

    [[test.sample_mapper.transformations]]
    type = "Resize"
    shape = [720, 1280]