[model]
type = "MMOneStageDetector"
category_mapping = {"pedestrian" = 0, "rider" = 1, "car" = 2, "truck" = 3, "bus" = 4, "train" = 5, "motorcycle" = 6, "bicycle" = 7, "traffic light" = 8, "traffic sign" = 9}
model_base = "mmdet://_base_/models/retinanet_r50_fpn.py"
pixel_mean = [123.675, 116.28, 103.53]
pixel_std = [58.395, 57.12, 57.375]
weights = "bdd100k://retinanet_r50_fpn_3x_det_bdd100k.pth"