[[config]]
path = "../configs/datasets/bdd100k/sem_seg.toml"

[[config]]
path = "../configs/models/mmsegmentation/deeplabv3plus_R_50_D8.toml"

[model]
    [model.optimizer]
    type = "SGD"
    lr = 0.02
    kwargs = {"momentum" = 0.9}

    [model.lr_scheduler]
    type = "MultiStepLR"
    kwargs = {"milestones" = [50, 100]}

[launch]
samples_per_gpu = 2
workers_per_gpu = 0

[trainer]
max_steps = 200
log_every_n_steps = 50
check_val_every_n_epoch = 10