[[config]]
path = "../configs/datasets/bdd100k/detect.toml"

[[config]]
path = "../configs/models/mmdetection/faster_rcnn_R_50_FPN.toml"

[launch]
samples_per_gpu = 1
workers_per_gpu = 0

[trainer]
max_steps = 1
