[[config]]
path = "../configs/datasets/bdd100k/ins_seg.toml"

[[config]]
path = "../configs/models/mmdetection/mask_rcnn_R_50_FPN.toml"

[model]
    [model.optimizer]
    type = "SGD"
    lr = 0.02
    kwargs = {"momentum" = 0.9}

    [model.lr_scheduler]
    type = "MultiStepLR"
    kwargs = {"milestones" = [50, 100]}

[launch]
samples_per_gpu = 1
workers_per_gpu = 0

[trainer]
max_steps = 1