[model]
type = "DetectorWrapper"
    [model.detection]
    type = "D2GeneralizedRCNN"
    model_base = "faster-rcnn/r50-fpn"
    num_classes = 10

[solver]
images_per_gpu = 2
lr_policy = "WarmupMultiStepLR"
base_lr = 0.002
max_iters = 1000
steps = [100]
checkpoint_period = 100
eval_period = 100
eval_metrics = ['detect']

[[train]]
name = "bdd100k_sample_train"
type = "scalabel"
annotations = "openmt/engine/testcases/detect/bdd100k-samples/annotation.json"
data_root = "openmt/engine/testcases/detect/bdd100k-samples/images"

[[test]]
name = "bdd100k_sample_val"
type = "scalabel"
annotations = "openmt/engine/testcases/detect/bdd100k-samples/annotation.json"
data_root = "openmt/engine/testcases/detect/bdd100k-samples/images"

[dataloader]
workers_per_gpu = 0
train_max_size = 1280
test_max_size = 1280
    [dataloader.data_backend]
    type = "HDF5Backend"
    [dataloader.ref_sampling_cfg]
    type = 'uniform'
    scope = 1
    num_ref_imgs = 0

[launch]
weights = "detectron2"