[model]
type = "DetectorWrapper"
    [detection]
    type = "D2GeneralizedRCNN"
    model_base = "faster-rcnn/r50-fpn"
    weights = "detectron2"
    num_classes = 10

[solver]
images_per_batch = 2
lr_policy = "WarmupMultiStepLR"
base_lr = 0.02
steps = [1000, 2000]
max_iters = 10000
checkpoint_period = 2000
eval_period = 2000

[[train]]
name = "bdd100k_train"
type = "coco"
annotation_file = "./data/bdd100k_labels_images_train_coco_release.json"
data_root = "./data/bdd100k/images/100k/train"

[[test]]
name = "bdd100k_val"
type = "coco"
annotation_file = "./data/bdd100k_labels_images_val_coco_release.json"
data_root = "./data/bdd100k/images/100k/val"

[dataloader]
num_workers = 4
    [dataloader.sampling_cfg]
    type = 'uniform'
    scope = 1
    num_ref_imgs = 0
