[detection]
model_name = "faster-rcnn-r101-fpn"
base_cfg = "detectron2://COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml"
weights = "detectron2://COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml"
num_classes = 10

[solver]
images_per_batch = 16
lr_policy = "step"
base_lr = 0.02
steps = [1000, 2000]
max_iters = 10000
checkpoint_period = 2000
eval_period = 2000

[[train]]
name = "bdd100k_train"
type = "coco"
annotation_file = "./data/bdd100k_labels_images_train_coco_release.json"
data_root = "./data/bdd100k/images/100k/train"

[[test]]
name = "bdd100k_val"
type = "coco"
annotation_file = "./data/bdd100k_labels_images_val_coco_release.json"
data_root = "./data/bdd100k/images/100k/val"

[dataloader]
num_workers = 16
