[[config]]
path = "../configs/datasets/bdd100k/seg_track.toml"

[[config]]
path = "../configs/models/mmdetection/mask_qdtrack_R_50_FPN.toml"

[model]
    [model.optimizer]
    type = "SGD"
    lr = 0.001

    [model.lr_scheduler]
    type = "MultiStepLR"
    warmup = "constant"
    kwargs = {"milestones" = [9, 11]}

[launch]
samples_per_gpu = 1
workers_per_gpu = 0

[trainer]
max_steps = 2
log_every_n_steps = 50
