[[train]]
name = "bdd100k_det_sample_train"
type = "COCO"
annotations = "vis4d/engine/testcases/detect/bdd100k-samples/annotation_coco.json"
data_root = "vis4d/engine/testcases/detect/bdd100k-samples/images"
config_path = "vis4d/engine/testcases/detect/bdd100k-samples/config.toml"
num_processes = 0
    [train.ref_sampler]
    type = 'uniform'
    scope = 1
    num_ref_imgs = 0

    [[train.sample_mapper.transformations]]
    type = "Resize"
    shape = [360, 640]
    scale_range = [1.2, 1.5]
    interpolation = "bicubic"

    [[train.sample_mapper.transformations]]
    type = "Resize"
    shape = [
        [360, 640],
        [480, 960]
    ]
    keep_ratio = true
    multiscale_mode = "list"

    [[train.sample_mapper.transformations]]
    type = "KorniaAugmentationWrapper"
    kornia_type = "RandomHorizontalFlip"
    prob = 0.5

[[test]]
name = "bdd100k_det_sample_val"
type = "Scalabel"
annotations = "vis4d/engine/testcases/detect/bdd100k-samples/annotation.json"
data_root = "vis4d/engine/testcases/detect/bdd100k-samples/images"
config_path = "vis4d/engine/testcases/detect/bdd100k-samples/config.toml"
num_processes = 0
eval_metrics = ["detect"]
    [[test.sample_mapper.transformations]]
    type = "Resize"
    shape = [720, 1280]
