[[train]]
name = "bdd100k_seg_track_sample_train"
type = "BDD100K"
annotations = "vis4d/engine/testcases/track/bdd100k-samples/labels/"
data_root = "vis4d/engine/testcases/track/bdd100k-samples/images/"
config_path = "seg_track"
num_processes = 0
cache_as_binary = true
compute_global_instance_ids = true
    [train.sample_mapper]
    fields_to_load = ["boxes2d", "instance_masks"]

        [train.ref_sampler]
        type = 'uniform'
        scope = 2
        num_ref_imgs = 1
        skip_nomatch_samples = true

    [[train.sample_mapper.transformations]]
    type = "Resize"
    shape = [360, 640]

    [[train.sample_mapper.transformations]]
    type = "KorniaAugmentationWrapper"
    kornia_type = "RandomHorizontalFlip"
    prob = 0.5

[[train]]
name = "bdd100k_ins_seg_sample_train"
type = "COCO"
annotations = "vis4d/engine/testcases/detect/bdd100k-samples/annotation_coco.json"
data_root = "vis4d/engine/testcases/detect/bdd100k-samples/images/"
config_path = "vis4d/engine/testcases/detect/bdd100k-samples/ins_seg_config.toml"
num_processes = 0
    [train.sample_mapper]
    fields_to_load = ["boxes2d", "instance_masks"]

        [train.ref_sampler]
        scope = 0
        num_ref_imgs = 1

    [[train.sample_mapper.transformations]]
    type = "Resize"
    shape = [360, 640]

    [[train.sample_mapper.transformations]]
    type = "KorniaAugmentationWrapper"
    kornia_type = "RandomHorizontalFlip"
    prob = 0.5

[[test]]
name = "bdd100k_sample_val"
type = "BDD100K"
annotations = "vis4d/engine/testcases/track/bdd100k-samples/labels/"
data_root = "vis4d/engine/testcases/track/bdd100k-samples/images/"
eval_metrics = ["detect", "track", "ins_seg", "seg_track"]
config_path = "seg_track"
num_processes = 0
    [test.sample_mapper]
    fields_to_load = ["boxes2d", "instance_masks"]

        [[test.sample_mapper.transformations]]
        type = "Resize"
        shape = [720, 1280]
